name: Validate SUT can stand up

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker using Docker's official script
        run: |
            curl -fsSL https://get.docker.com -o get-docker.sh 
            sudo sh get-docker.sh
        continue-on-error: false
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
      - name: Checkout Repository for access
        uses: actions/checkout@v4
      - name: Parse docker-compose for unique images
        run: |
            ls
            images=$(cat config/docker-compose.yml | grep "image:" | awk '{print $2}' | tr -d '"' | tr '\n' ' ')
            echo "IMAGES=$images" >> $GITHUB_ENV
            echo "Extracted images: $images"
        continue-on-error: false
      #TODO: update where we look for the docker-compose
      - name: Start application-specific services using Docker Compose
        run: docker-compose up -d
        continue-on-error: false
      # TODO: sleep
      # TODO: validate that containers are up
      # TODO: validate that setup_complete emitted (might need to define another env var)
      # TODO: take "workload" dir as input; dynamically iterate through test composer scripts; ensure they have non-zero exit code